### ISSUE TITLE
Leaderboards for at least one game are not updating despite the website having new times. 

### ISSUE THREAD

**Issue by TCayton** [dl00/speedrun-browser-android#7]
I'm having an issue seeing the current world record for Hades speedruns. 
![Screenshot_20210117_173100_danb speedrunbrowser](https://user-images.githubusercontent.com/47906263/104850978-11d9a580-58ea-11eb-88b0-c910971b92c0.jpg)

This was taken at 17:31 UTC on 2021.01.17. The new world record on the official website however was broken on the 10th of Jan and verified on the 15th. I've tried clearing my cache but this didn't seem to have an effect. 

**To Reproduce**
1. Find the Hades Leaderboards and ensure you are looking at the Any Heat, Unseeded runs for version 1.37+. 
2. The no. 1 spot should be held by Lili at 5m 57s but for me I only see the older record as shown in the above image.

**Smartphone (please complete the following information):**
 - Device: Huawei P20 Pro
 - OS: Android 10
 - App Version: 1.18

**Comment by dl00** [comment]
hi TCayton, the Speedrun.com site has currently disabled some API features which the app requires in order to pull the latest runs. I was told privately by the site managers that they expect these API features to be restored within the next week or two.

Very sorry for the confusion! Check in on this other issue https://github.com/dl00/speedrun-browser-android/issues/6 for updates. Thanks!
